<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>87805318-2226-4d72-be16-a42e3b30fc13</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to `Hello {Name}!` ;
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
